page.get_by_label("First Name").click()
page.get_by_label("Last Name").click()
page.get_by_label("Email").click()
page.get_by_label("Phone").click()
page.locator(".select__input-container").first.click()
page.get_by_label("Location (City)*").fill("Oak Park")
page.get_by_role("option", name="Oak Park, Illinois, United").click()
page.get_by_label("Resume/CV*").get_by_role("button", name="Attach").click()
page.get_by_label("Resume/CV*").get_by_role("button", name="Attach").set_input_files("2024-DEC-SongerResume.pdf")
page.get_by_label("LinkedIn Profile").click()
page.get_by_label("Website").click()
page.get_by_label("Website").fill("https://songer.pro")
page.get_by_text("Are you legally authorized to").click()
page.get_by_label("Toggle flyout").first.click()
page.get_by_role("option", name="Yes").click()
page.get_by_text("Will you now or in the future").click()
page.get_by_label("Toggle flyout").nth(1).click()
page.get_by_role("option", name="No").click()
page.get_by_text("Have you been employed by").click()
page.get_by_label("Toggle flyout").nth(2).click()
page.get_by_role("option", name="No").click()
page.get_by_label("By clicking this box and").check()