countries = [
    {"country": "Afghanistan", "isoShort": "AF", "isoLong": "AFG", "code": 93},
    {"country": "Albania", "isoShort": "AL", "isoLong": "ALB", "code": 355},
    {"country": "Algeria", "isoShort": "DZ", "isoLong": "DZA", "code": 213},
    {"country": "American Samoa", "isoShort": "AS", "isoLong": "ASM", "code": 1684},
    {"country": "Andorra", "isoShort": "AD", "isoLong": "AND", "code": 376},
    {"country": "Angola", "isoShort": "AO", "isoLong": "AGO", "code": 244},
    {"country": "Anguilla", "isoShort": "AI", "isoLong": "AIA", "code": 1264},
    {"country": "Antarctica", "isoShort": "AQ", "isoLong": "ATA", "code": 672},
    {"country": "Antarctica", "isoShort": "AQ", "isoLong": "ATA", "code": 64},
    {"country": "Antigua and Barbuda", "isoShort": "AG", "isoLong": "ATG", "code": 1268},
    {"country": "Argentina", "isoShort": "AR", "isoLong": "ARG", "code": 54},
    {"country": "Armenia", "isoShort": "AM", "isoLong": "ARM", "code": 374},
    {"country": "Aruba", "isoShort": "AW", "isoLong": "ABW", "code": 297},
    {"country": "Ascension Island", "isoShort": "AC", "isoLong": "ASC", "code": 247},
    {"country": "Australia", "isoShort": "AU", "isoLong": "AUS", "code": 61},
    {"country": "Austria", "isoShort": "AT", "isoLong": "AUT", "code": 43},
    {"country": "Azerbaijan", "isoShort": "AZ", "isoLong": "AZE", "code": 994},
    {"country": "Bahamas", "isoShort": "BS", "isoLong": "BHS", "code": 1242},
    {"country": "Bahrain", "isoShort": "BH", "isoLong": "BHR", "code": 973},
    {"country": "Bangladesh", "isoShort": "BD", "isoLong": "BGD", "code": 880},
    {"country": "Barbados", "isoShort": "BB", "isoLong": "BRB", "code": 1246},
    {"country": "Belarus", "isoShort": "BY", "isoLong": "BLR", "code": 375},
    {"country": "Belgium", "isoShort": "BE", "isoLong": "BEL", "code": 32},
    {"country": "Belize", "isoShort": "BZ", "isoLong": "BLZ", "code": 501},
    {"country": "Benin", "isoShort": "BJ", "isoLong": "BEN", "code": 229},
    {"country": "Bermuda", "isoShort": "BM", "isoLong": "BMU", "code": 1441},
    {"country": "Bhutan", "isoShort": "BT", "isoLong": "BTN", "code": 975},
    {"country": "Bolivia", "isoShort": "BO", "isoLong": "BOL", "code": 591},
    {"country": "Bosnia and Herzegovina", "isoShort": "BA", "isoLong": "BIH", "code": 387},
    {"country": "Botswana", "isoShort": "BW", "isoLong": "BWA", "code": 267},
    {"country": "Brazil", "isoShort": "BR", "isoLong": "BRA", "code": 55},
    {"country": "British Virgin Islands", "isoShort": "VG", "isoLong": "VGB", "code": 1284},
    {"country": "Brunei", "isoShort": "BN", "isoLong": "BRN", "code": 673},
    {"country": "Bulgaria", "isoShort": "BG", "isoLong": "BGR", "code": 359},
    {"country": "Burkina Faso", "isoShort": "BF", "isoLong": "BFA", "code": 226},
    {"country": "Burma (Myanmar)", "isoShort": "MM", "isoLong": "MMR", "code": 95},
    {"country": "Burundi", "isoShort": "BI", "isoLong": "BDI", "code": 257},
    {"country": "Cambodia", "isoShort": "KH", "isoLong": "KHM", "code": 855},
    {"country": "Cameroon", "isoShort": "CM", "isoLong": "CMR", "code": 237},
    {"country": "Canada", "isoShort": "CA", "isoLong": "CAN", "code": 1},
    {"country": "Cape Verde", "isoShort": "CV", "isoLong": "CPV", "code": 238},
    {"country": "Cayman Islands", "isoShort": "KY", "isoLong": "CYM", "code": 1345},
    {"country": "Central African Republic", "isoShort": "CF", "isoLong": "CAF", "code": 236},
    {"country": "Chad", "isoShort": "TD", "isoLong": "TCD", "code": 235},
    {"country": "Chile", "isoShort": "CL", "isoLong": "CHL", "code": 56},
    {"country": "China", "isoShort": "CN", "isoLong": "CHN", "code": 86},
    {"country": "Christmas Island", "isoShort": "CX", "isoLong": "CXR", "code": 61},
    {"country": "Cocos (Keeling) Islands", "isoShort": "CC", "isoLong": "CCK", "code": 61},
    {"country": "Colombia", "isoShort": "CO", "isoLong": "COL", "code": 57},
    {"country": "Comoros", "isoShort": "KM", "isoLong": "COM", "code": 269},
    {"country": "Congo", "isoShort": "CG", "isoLong": "COG", "code": 242},
    {"country": "Cook Islands", "isoShort": "CK", "isoLong": "COK", "code": 682},
    {"country": "Costa Rica", "isoShort": "CR", "isoLong": "CRC", "code": 506},
    {"country": "Croatia", "isoShort": "HR", "isoLong": "HRV", "code": 385},
    {"country": "Cuba", "isoShort": "CU", "isoLong": "CUB", "code": 53},
    {"country": "Cyprus", "isoShort": "CY", "isoLong": "CYP", "code": 357},
    {"country": "Czech Republic", "isoShort": "CZ", "isoLong": "CZE", "code": 420},
    {"country": "Democratic Republic of the Congo", "isoShort": "CD", "isoLong": "COD", "code": 243},
    {"country": "Denmark", "isoShort": "DK", "isoLong": "DNK", "code": 45},
    {"country": "Diego Garcia", "isoShort": "DG", "isoLong": "DGA", "code": 246},
    {"country": "Djibouti", "isoShort": "DJ", "isoLong": "DJI", "code": 253},
    {"country": "Dominica", "isoShort": "DM", "isoLong": "DMA", "code": 1767},
    {"country": "Dominican Republic", "isoShort": "DO", "isoLong": "DOM", "code": 1809},
    {"country": "Dominican Republic", "isoShort": "DO", "isoLong": "DOM", "code": 1829},
    {"country": "Dominican Republic", "isoShort": "DO", "isoLong": "DOM", "code": 1849},
    {"country": "Ecuador", "isoShort": "EC", "isoLong": "ECU", "code": 593},
    {"country": "Egypt", "isoShort": "EG", "isoLong": "EGY", "code": 20},
    {"country": "El Salvador", "isoShort": "SV", "isoLong": "SLV", "code": 503},
    {"country": "Equatorial Guinea", "isoShort": "GQ", "isoLong": "GNQ", "code": 240},
    {"country": "Eritrea", "isoShort": "ER", "isoLong": "ERI", "code": 291},
    {"country": "Estonia", "isoShort": "EE", "isoLong": "EST", "code": 372},
    {"country": "Ethiopia", "isoShort": "ET", "isoLong": "ETH", "code": 251},
    {"country": "Falkland Islands", "isoShort": "FK", "isoLong": "FLK", "code": 500},
    {"country": "Faroe Islands", "isoShort": "FO", "isoLong": "FRO", "code": 298},
    {"country": "Fiji", "isoShort": "FJ", "isoLong": "FJI", "code": 679},
    {"country": "Finland", "isoShort": "FI", "isoLong": "FIN", "code": 358},
    {"country": "France", "isoShort": "FR", "isoLong": "FRA", "code": 33},
    {"country": "French Guiana", "isoShort": "GF", "isoLong": "GUF", "code": 594},
    {"country": "French Polynesia", "isoShort": "PF", "isoLong": "PYF", "code": 689},
    {"country": "Gabon", "isoShort": "GA", "isoLong": "GAB", "code": 241},
    {"country": "Gambia", "isoShort": "GM", "isoLong": "GMB", "code": 220},
    {"country": "Georgia", "isoShort": "GE", "isoLong": "GEO", "code": 995},
    {"country": "Germany", "isoShort": "DE", "isoLong": "DEU", "code": 49},
    {"country": "Ghana", "isoShort": "GH", "isoLong": "GHA", "code": 233},
    {"country": "Gibraltar", "isoShort": "GI", "isoLong": "GIB", "code": 350},
    {"country": "Greece", "isoShort": "GR", "isoLong": "GRC", "code": 30},
    {"country": "Greenland", "isoShort": "GL", "isoLong": "GRL", "code": 299},
    {"country": "Grenada", "isoShort": "GD", "isoLong": "GRD", "code": 1473},
    {"country": "Guadeloupe", "isoShort": "GP", "isoLong": "GLP", "code": 590},
    {"country": "Guam", "isoShort": "GU", "isoLong": "GUM", "code": 1671},
    {"country": "Guatemala", "isoShort": "GT", "isoLong": "GTM", "code": 502},
    {"country": "Guinea", "isoShort": "GN", "isoLong": "GIN", "code": 224},
    {"country": "Guinea-Bissau", "isoShort": "GW", "isoLong": "GNB", "code": 245},
    {"country": "Guyana", "isoShort": "GY", "isoLong": "GUY", "code": 592},
    {"country": "Haiti", "isoShort": "HT", "isoLong": "HTI", "code": 509},
    {"country": "Holy See (Vatican City)", "isoShort": "VA", "isoLong": "VAT", "code": 39},
    {"country": "Honduras", "isoShort": "HN", "isoLong": "HND", "code": 504},
    {"country": "Hong Kong", "isoShort": "HK", "isoLong": "HKG", "code": 852},
    {"country": "Hungary", "isoShort": "HU", "isoLong": "HUN", "code": 36},
    {"country": "Iceland", "isoShort": "IS", "isoLong": "IS", "code": 354},
    {"country": "India", "isoShort": "IN", "isoLong": "IND", "code": 91},
    {"country": "Indonesia", "isoShort": "ID", "isoLong": "IDN", "code": 62},
    {"country": "Iran", "isoShort": "IR", "isoLong": "IRN", "code": 98},
    {"country": "Iraq", "isoShort": "IQ", "isoLong": "IRQ", "code": 964},
    {"country": "Ireland", "isoShort": "IE", "isoLong": "IRL", "code": 353},
    {"country": "Isle of Man", "isoShort": "IM", "isoLong": "IMN", "code": 44},
    {"country": "Israel", "isoShort": "IL", "isoLong": "ISR", "code": 972},
    {"country": "Italy", "isoShort": "IT", "isoLong": "ITA", "code": 39},
    {"country": "Ivory Coast (Côte d'Ivoire)", "isoShort": "CI", "isoLong": "CIV", "code": 225},
    {"country": "Jamaica", "isoShort": "JM", "isoLong": "JAM", "code": 1876},
    {"country": "Japan", "isoShort": "JP", "isoLong": "JPN", "code": 81},
    {"country": "Jersey", "isoShort": "JE", "isoLong": "JEY", "code": 44},
    {"country": "Jordan", "isoShort": "JO", "isoLong": "JOR", "code": 962},
    {"country": "Kazakhstan", "isoShort": "KZ", "isoLong": "KAZ", "code": 7},
    {"country": "Kenya", "isoShort": "KE", "isoLong": "KEN", "code": 254},
    {"country": "Kiribati", "isoShort": "KI", "isoLong": "KIR", "code": 686},
    {"country": "Kuwait", "isoShort": "KW", "isoLong": "KWT", "code": 965},
    {"country": "Kyrgyzstan", "isoShort": "KG", "isoLong": "KGZ", "code": 996},
    {"country": "Laos", "isoShort": "LA", "isoLong": "LAO", "code": 856},
    {"country": "Latvia", "isoShort": "LV", "isoLong": "LVA", "code": 371},
    {"country": "Lebanon", "isoShort": "LB", "isoLong": "LBN", "code": 961},
    {"country": "Lesotho", "isoShort": "LS", "isoLong": "LSO", "code": 266},
    {"country": "Liberia", "isoShort": "LR", "isoLong": "LBR", "code": 231},
    {"country": "Libya", "isoShort": "LY", "isoLong": "LBY", "code": 218},
    {"country": "Liechtenstein", "isoShort": "LI", "isoLong": "LIE", "code": 423},
    {"country": "Lithuania", "isoShort": "LT", "isoLong": "LTU", "code": 370},
    {"country": "Luxembourg", "isoShort": "LU", "isoLong": "LUX", "code": 352},
    {"country": "Macau", "isoShort": "MO", "isoLong": "MAC", "code": 853},
    {"country": "Macedonia", "isoShort": "MK", "isoLong": "MKD", "code": 389},
    {"country": "Madagascar", "isoShort": "MG", "isoLong": "MDG", "code": 261},
    {"country": "Malawi", "isoShort": "MW", "isoLong": "MWI", "code": 265},
    {"country": "Malaysia", "isoShort": "MY", "isoLong": "MYS", "code": 60},
    {"country": "Maldives", "isoShort": "MV", "isoLong": "MDV", "code": 960},
    {"country": "Mali", "isoShort": "ML", "isoLong": "MLI", "code": 223},
    {"country": "Malta", "isoShort": "MT", "isoLong": "MLT", "code": 356},
    {"country": "Marshall Islands", "isoShort": "MH", "isoLong": "MHL", "code": 692},
    {"country": "Martinique", "isoShort": "MQ", "isoLong": "MTQ", "code": 596},
    {"country": "Mauritania", "isoShort": "MR", "isoLong": "MRT", "code": 222},
    {"country": "Mauritius", "isoShort": "MU", "isoLong": "MUS", "code": 230},
    {"country": "Mayotte", "isoShort": "YT", "isoLong": "MYT", "code": 262},
    {"country": "Mexico", "isoShort": "MX", "isoLong": "MEX", "code": 52},
    {"country": "Micronesia", "isoShort": "FM", "isoLong": "FSM", "code": 691},
    {"country": "Moldova", "isoShort": "MD", "isoLong": "MDA", "code": 373},
    {"country": "Monaco", "isoShort": "MC", "isoLong": "MCO", "code": 377},
    {"country": "Mongolia", "isoShort": "MN", "isoLong": "MNG", "code": 976},
    {"country": "Montenegro", "isoShort": "ME", "isoLong": "MNE", "code": 382},
    {"country": "Montserrat", "isoShort": "MS", "isoLong": "MSR", "code": 1664},
    {"country": "Morocco", "isoShort": "MA", "isoLong": "MAR", "code": 212},
    {"country": "Mozambique", "isoShort": "MZ", "isoLong": "MOZ", "code": 258},
    {"country": "Namibia", "isoShort": "NA", "isoLong": "NAM", "code": 264},
    {"country": "Nauru", "isoShort": "NR", "isoLong": "NRU", "code": 674},
    {"country": "Nepal", "isoShort": "NP", "isoLong": "NPL", "code": 977},
    {"country": "Netherlands", "isoShort": "NL", "isoLong": "NLD", "code": 31},
    {"country": "Netherlands Antilles", "isoShort": "AN", "isoLong": "ANT", "code": 599},
    {"country": "New Caledonia", "isoShort": "NC", "isoLong": "NCL", "code": 687},
    {"country": "New Zealand", "isoShort": "NZ", "isoLong": "NZL", "code": 64},
    {"country": "Nicaragua", "isoShort": "NI", "isoLong": "NIC", "code": 505},
    {"country": "Niger", "isoShort": "NE", "isoLong": "NER", "code": 227},
    {"country": "Nigeria", "isoShort": "NG", "isoLong": "NGA", "code": 234},
    {"country": "Niue", "isoShort": "NU", "isoLong": "NIU", "code": 683},
    {"country": "Norfolk Island", "isoShort": "NF", "isoLong": "NFK", "code": 672},
    {"country": "North Korea", "isoShort": "KP", "isoLong": "PRK", "code": 850},
    {"country": "Northern Mariana Islands", "isoShort": "MP", "isoLong": "MNP", "code": 1670},
    {"country": "Norway", "isoShort": "NO", "isoLong": "NOR", "code": 47},
    {"country": "Oman", "isoShort": "OM", "isoLong": "OMN", "code": 968},
    {"country": "Pakistan", "isoShort": "PK", "isoLong": "PAK", "code": 92},
    {"country": "Palau", "isoShort": "PW", "isoLong": "PLW", "code": 680},
    {"country": "Palestine", "isoShort": "PS", "isoLong": "PSE", "code": 970},
    {"country": "Panama", "isoShort": "PA", "isoLong": "PAN", "code": 507},
    {"country": "Papua New Guinea", "isoShort": "PG", "isoLong": "PNG", "code": 675},
    {"country": "Paraguay", "isoShort": "PY", "isoLong": "PRY", "code": 595},
    {"country": "Peru", "isoShort": "PE", "isoLong": "PER", "code": 51},
    {"country": "Philippines", "isoShort": "PH", "isoLong": "PHL", "code": 63},
    {"country": "Pitcairn Islands", "isoShort": "PN", "isoLong": "PCN", "code": 870},
    {"country": "Poland", "isoShort": "PL", "isoLong": "POL", "code": 48},
    {"country": "Portugal", "isoShort": "PT", "isoLong": "PRT", "code": 351},
    {"country": "Puerto Rico", "isoShort": "PR", "isoLong": "PRI", "code": 1787},
    {"country": "Puerto Rico", "isoShort": "PR", "isoLong": "PRI", "code": 1939},
    {"country": "Qatar", "isoShort": "QA", "isoLong": "QAT", "code": 974},
    {"country": "Republic of the Congo", "isoShort": "CG", "isoLong": "COG", "code": 242},
    {"country": "Reunion Island", "isoShort": "RE", "isoLong": "REU", "code": 262},
    {"country": "Romania", "isoShort": "RO", "isoLong": "ROU", "code": 40},
    {"country": "Russia", "isoShort": "RU", "isoLong": "RUS", "code": 7},
    {"country": "Rwanda", "isoShort": "RW", "isoLong": "RWA", "code": 250},
    {"country": "Saint Barthelemy", "isoShort": "BL", "isoLong": "BLM", "code": 590},
    {"country": "Saint Helena", "isoShort": "SH", "isoLong": "SHN", "code": 290},
    {"country": "Saint Kitts and Nevis", "isoShort": "KN", "isoLong": "KNA", "code": 1869},
    {"country": "Saint Lucia", "isoShort": "LC", "isoLong": "LCA", "code": 1758},
    {"country": "Saint Martin", "isoShort": "MF", "isoLong": "MAF", "code": 590},
    {"country": "Saint Pierre and Miquelon", "isoShort": "PM", "isoLong": "SPM", "code": 508},
    {"country": "Saint Vincent and the Grenadines", "isoShort": "VC", "isoLong": "VCT", "code": 1784},
    {"country": "Samoa", "isoShort": "WS", "isoLong": "WSM", "code": 685},
    {"country": "San Marino", "isoShort": "SM", "isoLong": "SMR", "code": 378},
    {"country": "Sao Tome and Principe", "isoShort": "ST", "isoLong": "STP", "code": 239},
    {"country": "Saudi Arabia", "isoShort": "SA", "isoLong": "SAU", "code": 966},
    {"country": "Senegal", "isoShort": "SN", "isoLong": "SEN", "code": 221},
    {"country": "Serbia", "isoShort": "RS", "isoLong": "SRB", "code": 381},
    {"country": "Seychelles", "isoShort": "SC", "isoLong": "SYC", "code": 248},
    {"country": "Sierra Leone", "isoShort": "SL", "isoLong": "SLE", "code": 232},
    {"country": "Singapore", "isoShort": "SG", "isoLong": "SGP", "code": 65},
    {"country": "Sint Maarten", "isoShort": "SX", "isoLong": "SXM", "code": 1721},
    {"country": "Slovakia", "isoShort": "SK", "isoLong": "SVK", "code": 421},
    {"country": "Slovenia", "isoShort": "SI", "isoLong": "SVN", "code": 386},
    {"country": "Solomon Islands", "isoShort": "SB", "isoLong": "SLB", "code": 677},
    {"country": "Somalia", "isoShort": "SO", "isoLong": "SOM", "code": 252},
    {"country": "South Africa", "isoShort": "ZA", "isoLong": "ZAF", "code": 27},
    {"country": "South Korea", "isoShort": "KR", "isoLong": "KOR", "code": 82},
    {"country": "South Sudan", "isoShort": "SS", "isoLong": "SSD", "code": 211},
    {"country": "Spain", "isoShort": "ES", "isoLong": "ESP", "code": 34},
    {"country": "Sri Lanka", "isoShort": "LK", "isoLong": "LKA", "code": 94},
    {"country": "Sudan", "isoShort": "SD", "isoLong": "SDN", "code": 249},
    {"country": "Suriname", "isoShort": "SR", "isoLong": "SUR", "code": 597},
    {"country": "Svalbard", "isoShort": "SJ", "isoLong": "SJM", "code": 47},
    {"country": "Swaziland", "isoShort": "SZ", "isoLong": "SWZ", "code": 268},
    {"country": "Sweden", "isoShort": "SE", "isoLong": "SWE", "code": 46},
    {"country": "Switzerland", "isoShort": "CH", "isoLong": "CHE", "code": 41},
    {"country": "Syria", "isoShort": "SY", "isoLong": "SYR", "code": 963},
    {"country": "Taiwan", "isoShort": "TW", "isoLong": "TWN", "code": 886},
    {"country": "Tajikistan", "isoShort": "TJ", "isoLong": "TJK", "code": 992},
    {"country": "Tanzania", "isoShort": "TZ", "isoLong": "TZA", "code": 255},
    {"country": "Thailand", "isoShort": "TH", "isoLong": "THA", "code": 66},
    {"country": "Timor-Leste (East Timor)", "isoShort": "TL", "isoLong": "TLS", "code": 670},
    {"country": "Togo", "isoShort": "TG", "isoLong": "TGO", "code": 228},
    {"country": "Tokelau", "isoShort": "TK", "isoLong": "TKL", "code": 690},
    {"country": "Tonga Islands", "isoShort": "TO", "isoLong": "TON", "code": 676},
    {"country": "Trinidad and Tobago", "isoShort": "TT", "isoLong": "TTO", "code": 1868},
    {"country": "Tunisia", "isoShort": "TN", "isoLong": "TUN", "code": 216},
    {"country": "Turkey", "isoShort": "TR", "isoLong": "TUR", "code": 90},
    {"country": "Turkmenistan", "isoShort": "TM", "isoLong": "TKM", "code": 993},
    {"country": "Turks and Caicos Islands", "isoShort": "TC", "isoLong": "TCA", "code": 1649},
    {"country": "Tuvalu", "isoShort": "TV", "isoLong": "TUV", "code": 688},
    {"country": "Uganda", "isoShort": "UG", "isoLong": "UGA", "code": 256},
    {"country": "Ukraine", "isoShort": "UA", "isoLong": "UKR", "code": 380},
    {"country": "United Arab Emirates", "isoShort": "AE", "isoLong": "ARE", "code": 971},
    {"country": "United Kingdom", "isoShort": "GB", "isoLong": "GBR", "code": 44},
    {"country": "United States", "isoShort": "US", "isoLong": "USA", "code": 1},
    {"country": "Uruguay", "isoShort": "UY", "isoLong": "URY", "code": 598},
    {"country": "Uzbekistan", "isoShort": "UZ", "isoLong": "UZB", "code": 998},
    {"country": "Vanuatu", "isoShort": "VU", "isoLong": "VUT", "code": 678},
    {"country": "Venezuela", "isoShort": "VE", "isoLong": "VEN", "code": 58},
    {"country": "Vietnam", "isoShort": "VN", "isoLong": "VNM", "code": 84},
    {"country": "Wallis and Futuna", "isoShort": "WF", "isoLong": "WLF", "code": 681},
    {"country": "Western Sahara", "isoShort": "EH", "isoLong": "ESH", "code": 212},
    {"country": "Yemen", "isoShort": "YE", "isoLong": "YEM", "code": 967},
    {"country": "Zambia", "isoShort": "ZM", "isoLong": "ZMB", "code": 260},
    {"country": "Zimbabwe", "isoShort": "ZW", "isoLong": "ZWE", "code": 263},
]
